# Generated by Django 2.1.4 on 2018-12-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrecord',
            name='balance_loan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='installment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='interest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='late_fees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='month',
            field=models.CharField(blank=True, default='jan', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='previous_loan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='previous_share',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='share',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='total_share',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
