# Generated by Django 2.1.4 on 2018-12-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_society_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='slug',
            field=models.SlugField(max_length=2024, unique=True, verbose_name='slug'),
        ),
    ]
