# Generated by Django 2.1.4 on 2018-12-24 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20181224_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society', to='record.Society'),
        ),
    ]
