# Generated by Django 2.1.4 on 2019-01-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20181231_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
