# Generated by Django 2.1.4 on 2019-01-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_member_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_share', models.IntegerField(default=200)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.01, max_digits=2)),
                ('active', models.BooleanField(default=True)),
                ('society', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='record.Society')),
            ],
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
